/* ==========================================================
   BLUE LEGACY — CATALOGUE DES TITRES
========================================================== */

const BLUE_LEGACY_BOSS_TITLES = Object.freeze([
  ["one-piece", "Cartographe de l’impossible", "pirate", "🧭"],
  ["sea-emperor", "Pavillon des mers libres", "pirate", "🏴‍☠️"],
  ["worlds-greatest-fortune", "Maître des cargaisons", "pirate", "💰"],
  ["forgotten-history", "Lecteur des traces interdites", "pirate", "📜"],
  ["greatest-bounty-hunter", "Référence des chasseurs", "bounty-hunter", "🎯"],
  ["most-dangerous-criminals", "Traqueur de l’impossible", "bounty-hunter", "⛓️"],
  ["hunt-an-emperor", "Chasseur de pavillons noirs", "bounty-hunter", "⚔️"],
  ["contract-fortune", "Arbitre des grands contrats", "bounty-hunter", "📜"],
  ["break-the-chains", "Briseur de convois", "revolutionary", "⛓️"],
  ["reveal-void-century", "Porteur des vérités interdites", "revolutionary", "🗿"],
  ["build-underground-network", "Nœud de la résistance", "revolutionary", "🕸️"],
  ["found-free-nation", "Voix d’un peuple libre", "revolutionary", "🕊️"],
  ["admiral", "Rempart des grandes routes", "marine", "⚓"],
  ["fleet-admiral", "Commandant des flottes", "marine", "🎖️"],
  ["reform-the-marines", "Officier de la justice nouvelle", "marine", "⚖️"],
  ["greatest-marine-hero", "Espoir des populations", "marine", "🛡️"],
].map(([dreamId, name, faction, icon]) => {
  const specialties = {
    "one-piece": "intelligence", "sea-emperor": "charisma",
    "worlds-greatest-fortune": "intelligence", "forgotten-history": "intelligence",
    "greatest-bounty-hunter": "combat", "most-dangerous-criminals": "intelligence",
    "hunt-an-emperor": "haki", "contract-fortune": "intelligence",
    "break-the-chains": "combat", "reveal-void-century": "intelligence",
    "build-underground-network": "intelligence", "found-free-nation": "charisma",
    admiral: "combat", "fleet-admiral": "charisma",
    "reform-the-marines": "intelligence", "greatest-marine-hero": "health",
  };
  const stat = specialties[dreamId];
  return Object.freeze({
  id: `boss-${dreamId}-turning-point`,
  name,
  description: "Une épreuve majeure a donné une nouvelle portée à cette destinée.",
  unlockHint: "Surmonter un tournant majeur lié à ce rêve.",
  category: "exploit",
  rarity: "epic",
  icon,
  factions: [faction],
  timing: "mid",
  effects: {
    immediate: { [stat]: 7 },
    passive: { type: "statGainModifier", stat, value: 0.1 },
    popularity: 5,
  },
  sourceType: "decisive-dream",
  });
}));

window.BLUE_LEGACY_TITLE_FEMALE_NAMES = Object.freeze({
  "rival-chien-rouge": "Maîtresse du Chien Rouge",
  "rival-joker": "Maîtresse du Joker",
  "story-roger-golden-lion-rival": "Dompteuse du Lion d’Or",
  "boss-worlds-greatest-fortune-turning-point": "Maîtresse des cargaisons", "boss-forgotten-history-turning-point": "Lectrice des traces interdites",
  "boss-most-dangerous-criminals-turning-point": "Traqueuse de l’impossible", "boss-hunt-an-emperor-turning-point": "Chasseuse de pavillons noirs",
  "boss-break-the-chains-turning-point": "Briseuse de convois", "boss-reveal-void-century-turning-point": "Porteuse des vérités interdites",
  "boss-fleet-admiral-turning-point": "Commandante des flottes", "boss-reform-the-marines-turning-point": "Officière de la justice nouvelle",
  "personnalite-prudent": "Prudente", "personnalite-impulsif": "Impulsive", "personnalite-compatissant": "Compatissante",
  "personnalite-courageux": "Courageuse", "personnalite-ruse": "Rusée", "personnalite-curieux": "Curieuse",
  "personnalite-organise": "Organisée", "personnalite-creatif": "Créative", "personnalite-patient": "Patiente",
  "personnalite-arrogant": "Arrogante", "personnalite-discipline": "Disciplinée",
  "temperament-cunning": "Rusée", "temperament-brawler": "Bagarreuse",
  "roi-des-pirates": "Reine des Pirates", "empereur-des-mers": "Impératrice des mers", "seigneur-des-tresors": "Dame des trésors",
  "gardien-histoire-oubliee": "Gardienne de l’Histoire oubliée", "tombeur-empereur": "Tombeuse d’Empereur",
  "maitre-des-contrats": "Maîtresse des contrats", "chain-breaker": "Briseuse de chaînes", "truth-bearer": "Porteuse de la vérité",
  "founder-of-free-people": "Fondatrice du peuple libre", amiral: "Amirale", "amiral-en-chef": "Amirale en chef",
  "heros-de-la-marine": "Héroïne de la Marine", "veteran-des-mers": "Vétérane des mers",
  "prisonnier-des-mers": "Prisonnière des mers", "vaincu-par-les-mers": "Vaincue par les mers",
  "officier-de-renom": "Officière de renom", "chasseur-de-renom": "Chasseuse de renom",
  "maitre-de-la-traque": "Maîtresse de la traque", "traqueur-de-legende": "Traqueuse de légende",
  "navigateur-routes-impossibles": "Navigatrice des routes impossibles", "vice-amiral": "Vice-Amirale",
  "vice-commandant-de-dragon": "Vice-Commandante de Dragon", "heros-de-marineford": "Héroïne de Marineford",
  "liberateur-de-marineford": "Libératrice de Marineford", "tombeur-de-kaido": "Tombeuse de Kaido",
  "briseur-de-totto-land": "Briseuse de Totto Land", "rival-du-roux": "Rivale du Roux",
  "geolier-de-baggy": "Geôlière de Baggy",
  "evade-impel-down": "Évadée d’Impel Down", "traqueur-impel-down": "Traqueuse d’Impel Down",
  "liberateur-impel-down": "Libératrice d’Impel Down", "briseur-ombres": "Briseuse d’ombres",
  "tombeur-weevil": "Tombeuse de Weevil",
  "compagnon-legende": "Compagne de légende", "combattant-grand-line": "Combattante de Grand Line",
  "survivant-cent-tempetes": "Survivante des cent tempêtes",
});

window.SEA_OF_LEGENDS_TITLES = Object.freeze([
  ...[
    ["personnalite-prudent", "Prudent", "Tu observes les risques avant de t’engager."],
    ["personnalite-calme", "Calme", "Tu gardes la tête froide quand la situation se tend."],
    ["personnalite-impulsif", "Impulsif", "Tu agis souvent avant que le doute ne te retienne."],
    ["personnalite-compatissant", "Compatissant", "La souffrance des autres ne te laisse pas indifférent."],
    ["personnalite-courageux", "Courageux", "Tu avances même lorsque le danger est évident."],
    ["personnalite-ruse", "Rusé", "Tu sais trouver la faille dans les plans les mieux gardés."],
    ["personnalite-charismatique", "Charismatique", "Ta présence donne envie aux autres de t’écouter."],
    ["personnalite-curieux", "Curieux", "Chaque mystère mérite à tes yeux d’être exploré."],
    ["personnalite-pragmatique", "Pragmatique", "Tu privilégies les solutions qui fonctionnent réellement."],
    ["personnalite-organise", "Organisé", "Tu sais donner un ordre clair aux situations confuses."],
    ["personnalite-tenace", "Tenace", "Les revers renforcent ta détermination."],
    ["personnalite-creatif", "Créatif", "Tu inventes des réponses auxquelles personne ne s’attend."],
    ["personnalite-patient", "Patient", "Tu sais attendre le moment juste."],
    ["personnalite-responsable", "Responsable", "Tu assumes les conséquences de tes décisions."],
    ["personnalite-altruiste", "Altruiste", "Tu places volontiers l’intérêt des autres avant le tien."],
    ["personnalite-arrogant", "Arrogant", "Ta confiance laisse parfois peu de place au doute."],
    ["personnalite-discipline", "Discipliné", "La répétition et la maîtrise guident tes progrès."],
    ["personnalite-opportuniste", "Opportuniste", "Tu reconnais une occasion avant qu’elle ne disparaisse."],
  ].map(([id, name, description]) => Object.freeze({
    id,
    name,
    description,
    unlockHint: `Faire preuve d’un tempérament ${name.toLocaleLowerCase("fr-FR")} au cours d’une aventure.`,
    category: "personnalite",
    rarity: "common",
    icon: "◇",
    factions: [],
    timing: "any",
    effects: {},
    sourceType: "personality",
  })),
  {
    id: "ami-des-betes",
    name: "Ami des bêtes",
    description: "Même les compagnons les plus imprévisibles reconnaissent ta bonté.",
    unlockHint: "Libérer le chien naufragé et gagner sa confiance.",
    category: "crew",
    rarity: "uncommon",
    icon: "🐾",
    factions: [],
    timing: "early",
    effects: {
      immediate: { charisma: 3 },
      passive: { type: "statGainModifier", stat: "charisma", value: 0.05 },
      popularity: 2,
    },
  },
  {
    id: "temperament-cunning",
    name: "Rusé",
    description: "Tu préfères trouver la faille plutôt que forcer le passage.",
    unlockHint: "Faire preuve de ruse lors de la rencontre de Reverse Mountain.",
    category: "adventure",
    rarity: "uncommon",
    icon: "🧠",
    factions: [],
    timing: "early",
    effects: { immediate: { intelligence: 2, charisma: 1 } },
  },
  {
    id: "temperament-brawler",
    name: "Bagarreur",
    description: "Quand l’affrontement devient inévitable, tu es le premier à avancer.",
    unlockHint: "Prendre l’initiative lors de la rencontre de Reverse Mountain.",
    category: "adventure",
    rarity: "uncommon",
    icon: "👊",
    factions: [],
    timing: "early",
    effects: { immediate: { combat: 2, health: 1 } },
  },
  {
    id: "temperament-calm",
    name: "Calme",
    description: "Tu gardes la tête froide jusqu’au moment décisif.",
    unlockHint: "Garder son sang-froid lors de la rencontre de Reverse Mountain.",
    category: "adventure",
    rarity: "uncommon",
    icon: "🌊",
    factions: [],
    timing: "early",
    effects: { immediate: { haki: 2, intelligence: 1 } },
  },
  {
    id: "roi-des-pirates",
    name: "Roi des Pirates",
    description: "Tu as atteint le sommet de la piraterie.",
    unlockHint: "Accomplir le rêve de trouver le One Piece au terme d’une aventure.",
    category: "ultimate",
    rarity: "mythic",
    icon: "👑",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "empereur-des-mers",
    name: "Empereur des mers",
    description: "Ton pavillon impose sa loi jusque sur les mers les plus hostiles.",
    unlockHint: "Accomplir le rêve de devenir un Empereur des mers.",
    category: "ultimate",
    rarity: "mythic",
    careerScoreRarity: "legendary",
    icon: "👑",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 10 },
  },
  {
    id: "seigneur-des-tresors",
    name: "Seigneur des trésors",
    description: "Les richesses les mieux gardées ont fini entre tes mains.",
    unlockHint: "Accomplir le rêve d’amasser la plus grande fortune du monde.",
    category: "ultimate",
    rarity: "mythic",
    careerScoreRarity: "legendary",
    icon: "💎",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 10 },
  },
  {
    id: "gardien-histoire-oubliee",
    name: "Gardien de l’Histoire oubliée",
    description: "Tu portes une vérité que le monde cherchait à effacer.",
    unlockHint: "Accomplir le rêve de découvrir l’Histoire oubliée.",
    category: "ultimate",
    rarity: "mythic",
    careerScoreRarity: "legendary",
    icon: "📜",
    factions: ["pirate"],
    secret: true,
    timing: "final",
    finalTitle: true,
    effects: { popularity: 10 },
  },
  {
    id: "legende-des-chasseurs",
    name: "Légende des chasseurs",
    description: "Aucune cible ne semble pouvoir échapper à ta traque.",
    unlockHint: "Accomplir le rêve de devenir le plus grand chasseur de primes.",
    category: "ultimate",
    rarity: "mythic",
    icon: "🎯",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "fleau-des-criminels",
    name: "Fléau des criminels",
    description: "Ton nom suffit à inquiéter les équipages recherchés.",
    unlockHint: "Accomplir le rêve de capturer les criminels les plus dangereux.",
    category: "ultimate",
    rarity: "mythic",
    careerScoreRarity: "epic",
    icon: "⛓️",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 8 },
  },
  {
    id: "tombeur-empereur",
    name: "Tombeur d’Empereur",
    description: "Tu as fait vaciller l’une des plus grandes puissances des mers.",
    unlockHint: "Accomplir le rêve de traquer un Empereur.",
    category: "ultimate",
    rarity: "mythic",
    careerScoreRarity: "legendary",
    icon: "⚔️",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 10 },
  },
  {
    id: "maitre-des-contrats",
    name: "Maître des contrats",
    description: "Les missions les plus impossibles trouvent leur conclusion entre tes mains.",
    unlockHint: "Accomplir le rêve d’amasser une fortune grâce aux contrats.",
    category: "ultimate",
    rarity: "mythic",
    careerScoreRarity: "epic",
    icon: "📜",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 8 },
  },
  {
    id: "chain-breaker",
    name: "Briseur de chaînes",
    description: "Tu as fait tomber les réseaux qui prospéraient sur l’asservissement des plus faibles.",
    unlockHint: "Accomplir le rêve « Briser les chaînes » au cours d’une aventure Révolutionnaire.",
    category: "ultimate",
    rarity: "mythic",
    icon: "🔓",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "truth-bearer",
    name: "Porteur de la vérité",
    description: "Tu as rendu au monde une histoire que le Gouvernement mondial voulait effacer.",
    unlockHint: "Accomplir le rêve « Révéler le Siècle oublié » au cours d’une aventure Révolutionnaire.",
    category: "ultimate",
    rarity: "mythic",
    icon: "📜",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "architect-of-revolution",
    name: "Architecte de la Révolution",
    description: "Tu as bâti un réseau capable de porter la Révolution jusque dans les mers les plus lointaines.",
    unlockHint: "Accomplir le rêve « Bâtir le plus grand réseau clandestin » au cours d’une aventure Révolutionnaire.",
    category: "ultimate",
    rarity: "mythic",
    icon: "🕸️",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "founder-of-free-people",
    name: "Fondateur du peuple libre",
    description: "Tu as offert à un peuple un territoire que nul maître ne pourra lui reprendre.",
    unlockHint: "Accomplir le rêve « Fonder une nation libre » au cours d’une aventure Révolutionnaire.",
    category: "ultimate",
    rarity: "mythic",
    icon: "🕊️",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "amiral",
    name: "Amiral",
    description: "La Marine t’a confié l’un de ses plus hauts rangs.",
    unlockHint: "Accomplir le rêve de devenir Amiral.",
    category: "ultimate",
    rarity: "mythic",
    careerScoreRarity: "epic",
    icon: "⚓",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 8 },
  },
  {
    id: "amiral-en-chef",
    name: "Amiral en chef",
    description: "Tu diriges désormais les forces de la Marine.",
    unlockHint: "Accomplir le rêve de devenir Amiral en chef.",
    category: "ultimate",
    rarity: "mythic",
    icon: "⚓",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "justice-nouvelle",
    name: "Justice nouvelle",
    description: "Ta vision de la justice transforme durablement la Marine.",
    unlockHint: "Accomplir le rêve de réformer la Marine.",
    category: "ultimate",
    rarity: "mythic",
    careerScoreRarity: "legendary",
    icon: "⚖️",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 10 },
  },
  {
    id: "heros-de-la-marine",
    name: "Héros de la Marine",
    description: "Les civils comme les soldats racontent désormais tes exploits.",
    unlockHint: "Accomplir le rêve de devenir le plus grand héros de la Marine.",
    category: "ultimate",
    rarity: "mythic",
    careerScoreRarity: "epic",
    icon: "🛡️",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 8 },
  },
  {
    id: "veteran-des-mers",
    name: "Vétéran des mers",
    description: "Deux années d’aventure ont forgé une carrière mémorable.",
    unlockHint: "Atteindre le terme des vingt-quatre mois d’une aventure.",
    category: "adventure",
    rarity: "rare",
    icon: "🧭",
    factions: [],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 4 },
  },
  {
    id: "destin-brise",
    name: "Destin brisé",
    description: "Une grande aventure interrompue avant son accomplissement.",
    unlockHint: "Voir une aventure s’achever à la suite de blessures mortelles.",
    category: "destiny",
    rarity: "common",
    icon: "🌊",
    factions: [],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 1 },
  },
  {
    id: "prisonnier-des-mers",
    name: "Prisonnier des mers",
    description: "La route s’est achevée derrière les barreaux.",
    unlockHint: "Voir une aventure prendre fin par une capture.",
    category: "destiny",
    rarity: "common",
    icon: "⛓️",
    factions: [],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 1 },
  },
  {
    id: "vaincu-par-les-mers",
    name: "Vaincu par les mers",
    description: "Les dangers du voyage ont finalement eu raison de toi.",
    unlockHint: "Voir une aventure s’achever par une défaite.",
    category: "destiny",
    rarity: "common",
    icon: "⚓",
    factions: [],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 1 },
  },
  {
    id: "legende-inachevee",
    name: "Légende inachevée",
    description: "Ton voyage atteint son terme avant que ton rêve ne devienne réalité.",
    unlockHint: "Terminer une aventure avec moins de 60 de Popularité sans accomplir son rêve.",
    category: "destiny",
    rarity: "uncommon",
    icon: "📖",
    factions: [],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "capitaine-de-renom",
    name: "Capitaine de renom",
    description: "Ton pavillon n’a pas atteint son ambition ultime, mais son nom circule déjà bien au-delà de ton équipage.",
    unlockHint: "Terminer une aventure Pirate avec une Popularité comprise entre 60 et 74 sans accomplir son rêve.",
    category: "piracy",
    rarity: "rare",
    icon: "🏴‍☠️",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "terreurs-des-grandes-routes",
    name: "Terreur des grandes routes",
    description: "Les équipages comme les autorités ont appris à ne jamais ignorer ton pavillon.",
    unlockHint: "Terminer une aventure Pirate avec une Popularité comprise entre 75 et 89 sans accomplir son rêve.",
    category: "piracy",
    rarity: "epic",
    icon: "☠️",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "legende-des-mers",
    name: "Légende des mers",
    description: "Sans atteindre le rêve qui guidait ton voyage, tu es devenu une légende que toutes les mers racontent.",
    unlockHint: "Terminer une aventure Pirate avec au moins 90 de Popularité sans accomplir son rêve.",
    category: "piracy",
    rarity: "legendary",
    icon: "🌊",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "officier-de-renom",
    name: "Officier de renom",
    description: "Ta carrière n’a pas atteint son objectif ultime, mais tes états de service inspirent déjà le respect.",
    unlockHint: "Terminer une aventure Marine avec une Popularité comprise entre 60 et 74 sans accomplir son rêve.",
    category: "marine",
    rarity: "rare",
    icon: "⚓",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "rempart-de-la-justice",
    name: "Rempart de la justice",
    description: "Soldats et civils se souviennent d’un officier resté debout lorsque la justice vacillait.",
    unlockHint: "Terminer une aventure Marine avec une Popularité comprise entre 75 et 89 sans accomplir son rêve.",
    category: "marine",
    rarity: "epic",
    icon: "🛡️",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "legende-de-la-marine",
    name: "Légende de la Marine",
    description: "Même sans accomplir ton ambition ultime, ton nom appartient désormais à l’histoire de la Marine.",
    unlockHint: "Terminer une aventure Marine avec au moins 90 de Popularité sans accomplir son rêve.",
    category: "marine",
    rarity: "legendary",
    icon: "⚓",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "chasseur-de-renom",
    name: "Chasseur de renom",
    description: "Tes contrats et tes captures ont bâti une réputation que les commanditaires prennent au sérieux.",
    unlockHint: "Terminer une aventure de Chasseur de primes avec une Popularité comprise entre 60 et 74 sans accomplir son rêve.",
    category: "bounty-hunting",
    rarity: "rare",
    icon: "🎯",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "maitre-de-la-traque",
    name: "Maître de la traque",
    description: "Les cibles les plus prudentes savent désormais que tu peux retrouver presque n’importe qui.",
    unlockHint: "Terminer une aventure de Chasseur de primes avec une Popularité comprise entre 75 et 89 sans accomplir son rêve.",
    category: "bounty-hunting",
    rarity: "epic",
    icon: "🔍",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "traqueur-de-legende",
    name: "Traqueur de légende",
    description: "Ton rêve est resté hors de portée, mais ta carrière est devenue une référence pour tous les chasseurs.",
    unlockHint: "Terminer une aventure de Chasseur de primes avec au moins 90 de Popularité sans accomplir son rêve.",
    category: "bounty-hunting",
    rarity: "legendary",
    icon: "🎯",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "voix-de-la-revolte",
    name: "Voix de la révolte",
    description: "Ton rêve n’est pas entièrement réalisé, mais ta voix a éveillé des résistances qui ne s’éteindront plus.",
    unlockHint: "Terminer une aventure Révolutionnaire avec une Popularité comprise entre 60 et 74 sans accomplir son rêve.",
    category: "revolution",
    rarity: "rare",
    icon: "✊",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "etendard-de-la-liberte",
    name: "Étendard de la liberté",
    description: "Là où ton passage est connu, les opprimés savent désormais qu’une autre voie est possible.",
    unlockHint: "Terminer une aventure Révolutionnaire avec une Popularité comprise entre 75 et 89 sans accomplir son rêve.",
    category: "revolution",
    rarity: "epic",
    icon: "🚩",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "legende-de-la-revolution",
    name: "Légende de la Révolution",
    description: "Sans achever ton ambition ultime, tu as profondément marqué l’histoire de la lutte contre l’oppression.",
    unlockHint: "Terminer une aventure Révolutionnaire avec au moins 90 de Popularité sans accomplir son rêve.",
    category: "revolution",
    rarity: "legendary",
    icon: "🔥",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "navigateur-routes-impossibles",
    name: "Navigateur des routes impossibles",
    description: "Les courants les plus capricieux n’effacent plus ta route.",
    unlockHint: "Atteindre le Nouveau Monde au cours d’une aventure.",
    category: "exploration",
    rarity: "rare",
    icon: "🧭",
    factions: [],
    timing: "late",
    effects: {
      immediate: { intelligence: 6 },
      passive: { type: "statGainModifier", stat: "intelligence", value: 0.08 },
      popularity: 5,
    },
    condition: ({ game }) => Boolean(game?.visitedZoneIds?.includes("shinsekai")),
  },
  ...[
    ["supernova", "Supernova", "pirate", "☄️", { combat: 3, charisma: 5, haki: 2, bounty: 300000 }, 3],
    ["vice-amiral", "Vice-Amiral", "marine", "⚓", { health: 3, combat: 4, haki: 4, charisma: 2, bounty: 220000 }, 3],
    ["vice-commandant-de-dragon", "Vice-Commandant de Dragon", "revolutionary", "🐉", { intelligence: 4, charisma: 4, haki: 3, bounty: 260000 }, 3],
    ["cauchemar-des-pirates", "Cauchemar des pirates", "bounty-hunter", "🎯", { combat: 4, intelligence: 3, haki: 3, charisma: 2, bounty: 260000 }, 3],
  ].map(([id, name, faction, icon, immediate, popularity]) => ({
    id, name,
    description: "Une ascension exceptionnelle dans Paradise a imposé ce nom au monde.",
    unlockHint: {
      supernova: "Obtenu en faisant reconnaître ton nom comme l’un des nouveaux prodiges de la piraterie pendant Paradise.",
      "vice-amiral": "Obtenu après avoir prouvé ta capacité à commander une opération majeure de la Marine pendant Paradise.",
      "vice-commandant-de-dragon": "Obtenu après avoir gagné la confiance de Dragon au cours d’une opération révolutionnaire majeure dans Paradise.",
      "cauchemar-des-pirates": "Obtenu après avoir imposé ton nom aux pirates par une série de chasses décisives dans Paradise.",
    }[id],
    category: "prodige", rarity: "legendary", icon, factions: [faction], timing: "mid",
    sourceType: "legendary-talent",
    effects: { immediate, popularity },
  })),
  ...[
    ["fleau-de-marineford", "Fléau de Marineford", "pirate", "legendary", "☠️", { combat: 3, haki: 3, charisma: 2 }, 2],
    ["heros-de-marineford", "Héros de Marineford", "marine", "legendary", "⚓", { health: 3, haki: 3, charisma: 3 }, 2],
    ["arbitre-de-marineford", "Arbitre de Marineford", "bounty-hunter", "legendary", "🎯", { intelligence: 3, combat: 2, charisma: 3 }, 2],
    ["liberateur-de-marineford", "Libérateur de Marineford", "revolutionary", "legendary", "✊", { intelligence: 3, charisma: 4, haki: 2 }, 2],
  ].map(([id, name, faction, rarity, icon, immediate, popularity]) => ({
    id, name,
    description: "Trois décisions liées ont transformé la crise de Marineford en exploit historique.",
    unlockHint: "Accomplir presque parfaitement les trois étapes de la crise de Marineford.",
    category: "marineford", rarity, icon, factions: [faction], timing: "late",
    sourceType: "legendary-marineford",
    effects: { immediate, popularity },
  })),
  ...[
    ["tombeur-de-kaido", "Tombeur de Kaido", "mythic", "🐉", { health: 3, combat: 4, haki: 3 }, 3],
    ["briseur-de-totto-land", "Briseur de Totto Land", "legendary", "🍬", { intelligence: 3, combat: 3, charisma: 2 }, 3],
    ["rival-du-roux", "Rival du Roux", "mythic", "⚔️", { haki: 4, charisma: 4, health: 2 }, 3],
    ["fleau-de-barbe-noire", "Fléau de Barbe Noire", "mythic", "🌑", { intelligence: 4, combat: 3, haki: 3 }, 3],
    ["rival-de-barbe-blanche", "Fléau de Barbe Blanche", "mythic", "🌊", { health: 4, combat: 3, haki: 2 }, 3],
    ["geolier-de-baggy", "Geôlier de Baggy", "legendary", "⛓️", { intelligence: 4, charisma: 3, combat: 2 }, 3],
  ].map(([id, name, rarity, icon, immediate, popularity]) => ({
    id, name,
    description: "Une confrontation collective contre une puissance impériale s’est conclue par un résultat réel et mémorable.",
    unlockHint: "Réussir presque parfaitement les trois étapes d’un affrontement contre l’Empereur concerné.",
    category: "emperor", rarity, icon, factions: [], timing: "late",
    sourceType: "legendary-emperor",
    effects: { immediate, popularity },
  })),
  ...[
    ["fleau-taureau-vert", "Fléau du Taureau Vert", "legendary", "🌿", { combat: 3, intelligence: 3, haki: 2 }, 3],
    ["rival-chien-rouge", "Maître du Chien Rouge", "mythic", "🌋", { health: 3, combat: 3, haki: 3 }, 3],
    ["briseur-lumiere", "Briseur de lumière", "mythic", "✨", { intelligence: 3, combat: 3, haki: 3 }, 3],
    ["debout-sous-gravite", "Debout sous la gravité", "legendary", "☄️", { health: 3, intelligence: 3, charisma: 3 }, 3],
  ].map(([id, name, rarity, icon, immediate, popularity]) => ({
    id, name,
    description: "Une opération révolutionnaire a tenu face à l’une des plus grandes forces de la Marine.",
    unlockHint: "Réussir presque parfaitement les trois étapes de l’affrontement contre l’Amiral concerné.",
    category: "admiral", rarity, icon, factions: ["revolutionary"], timing: "late",
    sourceType: "legendary-admiral", effects: { immediate, popularity },
  })),
  {
    id:"champion-davy-back-fight", name:"Champion du Davy Back Fight",
    description:"Trois jeux pirates ont consacré ta maîtrise des règles du Davy Back Fight.",
    unlockHint:"Remporter au moins deux des trois épreuves du Davy Back Fight.",
    category:"davy", rarity:"legendary", icon:"🏁", factions:[], timing:"mid",
    sourceType:"legendary-davy", effects:{},
  },
  ...[
    ["evade-impel-down","Évadé d’Impel Down","pirate","⛓️",{health:3,combat:3,haki:2}],
    ["rempart-impel-down","Rempart d’Impel Down","marine","🛡️",{health:3,intelligence:3,charisma:2}],
    ["traqueur-impel-down","Traqueur d’Impel Down","bounty-hunter","🎯",{intelligence:3,combat:3,haki:2}],
    ["liberateur-impel-down","Libérateur d’Impel Down","revolutionary","✊",{intelligence:3,charisma:3,haki:2}],
  ].map(([id,name,faction,icon,immediate])=>({id,name,
    description:"Les six niveaux d’Impel Down n’ont pas arrêté cette mission.",
    unlockHint:"Réussir les trois étapes de l’arc Impel Down.", category:"impel-down",
    rarity:"legendary",icon,factions:[faction],timing:"late",sourceType:"legendary-impel-down",
    effects:{immediate,popularity:2},
  })),
  ...[
    ["briseur-ombres","Briseur d’ombres","🌑",{intelligence:3,combat:3,haki:2}],
    ["rival-joker","Maître du Joker","🦩",{intelligence:3,charisma:3,haki:2}],
    ["tombeur-weevil","Tombeur de Weevil","💥",{health:3,combat:3,haki:2}],
    ["rival-imperatrice-pirate","Fléau de l’Impératrice Pirate","🐍",{health:2,intelligence:3,charisma:3}],
    ["inebranlable-face-tyran","Inébranlable face au Tyran","🐾",{health:3,intelligence:3,haki:2}],
  ].map(([id,name,icon,immediate])=>({id,name,
    description:"Un Grand Corsaire a dû reconnaître que son décret ne suffisait plus à fermer la route.",
    unlockHint:"Réussir l’arc VS Grand Corsaire contre cet adversaire.",category:"warlord",
    rarity:"legendary",icon,factions:[],timing:"late",sourceType:"legendary-warlord",
    effects:{immediate,popularity:2},
  })),
  {
    id: "haki-observation",
    name: "Haki de l’Observation",
    description: "Tes sens perçoivent l’intention hostile avant que le danger ne frappe.",
    unlockHint: "Éveiller cette perception lors d’un tournant décisif.",
    category: "haki",
    rarity: "epic",
    icon: "👁️",
    factions: [],
    timing: "mid",
    effects: {
      immediate: { haki: 6, intelligence: 4, health: 2 },
      passive: { type: "statGainModifier", stat: "haki", value: 0.06 },
      popularity: 2,
    },
  },
  {
    id: "haki-armement",
    name: "Haki de l’Armement",
    description: "Ta volonté durcit ta garde et donne un poids nouveau à chaque impact.",
    unlockHint: "Éveiller cette force intérieure lors d’un tournant décisif.",
    category: "haki",
    rarity: "epic",
    icon: "🛡️",
    factions: [],
    timing: "mid",
    effects: {
      immediate: { combat: 6, health: 4, charisma: 2 },
      passive: { type: "statGainModifier", stat: "combat", value: 0.06 },
      popularity: 2,
    },
  },
  {
    id: "haki-des-rois",
    name: "Haki des Rois",
    description: "Une volonté souveraine s’impose sans arme et ébranle ceux qui cherchent à la soumettre.",
    unlockHint: "Manifester une volonté exceptionnelle lors d’une épreuve décisive.",
    category: "haki",
    rarity: "legendary",
    icon: "👑",
    factions: [],
    timing: "mid",
    effects: {
      immediate: { health: 4, combat: 4, haki: 4, intelligence: 4, charisma: 8 },
      popularity: 5,
    },
  },
  {
    id: "maitrise-haki-des-rois-plus",
    name: "Maîtrise du Haki des Rois+",
    description: "Ta volonté souveraine ne jaillit plus par accident : elle répond désormais à ton intention.",
    unlockHint: "Dépasser un Haki des Rois déjà éveillé lors d’une confrontation décisive.",
    category: "haki",
    rarity: "mythic",
    icon: "🌈",
    factions: [],
    timing: "late",
    effects: {
      // Bonus d’évolution uniquement : les effets du niveau de base ne sont
      // jamais rejoués lors du remplacement du Titre actif.
      immediate: { health: 1, combat: 1, haki: 1, intelligence: 1, charisma: 2 },
      popularity: 2,
    },
  },
  {
    id: "volonte-acier",
    name: "Rempart d’acier",
    description: "Ta Défense témoigne d’une résistance longuement éprouvée.",
    unlockHint: "Atteindre 45 en Défense.",
    category: "combat",
    rarity: "epic",
    icon: "🛡️",
    factions: [],
    timing: "late",
    effects: {
      immediate: { haki: 8 },
      passive: { type: "statGainModifier", stat: "haki", value: 0.1 },
      popularity: 7,
    },
    condition: ({ game }) => Number(game?.stats?.haki) >= 45,
  },
  {
    id: "compagnon-legende",
    name: "Compagnon de légende",
    description: "Un équipage nombreux a choisi de poursuivre cette aventure à tes côtés.",
    unlockHint: "Réunir au moins quatre membres d’équipage.",
    category: "crew",
    rarity: "rare",
    icon: "👥",
    factions: [],
    timing: "mid",
    effects: {
      immediate: { charisma: 5 },
      passive: { type: "statGainModifier", stat: "charisma", value: 0.08 },
      popularity: 4,
    },
    condition: ({ game }) => Number(game?.stats?.crew) >= 4,
  },
  {
    id: "stratege-des-courants",
    name: "Stratège des courants",
    description: "Tes plans ouvrent des routes que la force seule ne saurait atteindre.",
    unlockHint: "Atteindre 55 en Intelligence.",
    category: "exploration",
    rarity: "rare",
    icon: "🧠",
    factions: [],
    timing: "mid",
    effects: {
      immediate: { intelligence: 6 },
      passive: { type: "statGainModifier", stat: "intelligence", value: 0.1 },
      popularity: 5,
    },
    condition: ({ game }) => Number(game?.stats?.intelligence) >= 55,
  },
  {
    id: "voix-des-equipages",
    name: "Voix des équipages",
    description: "Des inconnus choisissent de te suivre lorsqu’ils entendent ton appel.",
    unlockHint: "Atteindre 70 en Charisme.",
    category: "crew",
    rarity: "rare",
    icon: "✨",
    factions: [],
    timing: "late",
    effects: {
      immediate: { charisma: 8 },
      passive: { type: "statGainModifier", stat: "charisma", value: 0.1 },
      popularity: 7,
    },
    condition: ({ game }) => Number(game?.stats?.charisma) >= 70,
  },
  {
    id: "combattant-grand-line",
    name: "Combattant de Grand Line",
    description: "Les affrontements successifs ont fait de toi une référence au combat.",
    unlockHint: "Atteindre 60 en Combat.",
    category: "combat",
    rarity: "rare",
    icon: "⚔️",
    factions: [],
    timing: "mid",
    effects: {
      immediate: { combat: 6 },
      passive: { type: "statGainModifier", stat: "combat", value: 0.1 },
      popularity: 5,
    },
    condition: ({ game }) => Number(game?.stats?.combat) >= 60,
  },
  {
    id: "survivant-cent-tempetes",
    name: "Survivant des cent tempêtes",
    description: "Ton endurance est devenue aussi célèbre que les dangers traversés.",
    unlockHint: "Atteindre 80 en Santé après avoir survécu à un événement dangereux.",
    category: "destiny",
    rarity: "epic",
    icon: "❤️",
    factions: [],
    timing: "late",
    effects: {
      immediate: { health: 8 },
      passive: { type: "statGainModifier", stat: "health", value: 0.1 },
      popularity: 7,
    },
    condition: ({ game }) => Number(game?.stats?.health) >= 80 &&
      Number(game?.achievementProgress?.dangerEventsSurvived) >= 1,
  },
  ...[
    ["story-roger-beyond-last-needle", "Au-delà de la dernière aiguille", "Roadstar n’était pas la fin : tu as su reconnaître la route qui restait à inventer.", "Atteindre une issue favorable lors de l’événement majeur de Roadstar.", "rare", "🧭", ({ game }) => game?.runMode === "story" && game?.storyId === "roger" && game?.flags?.storyRoadstarMajorSuccess === true],
    ["story-roger-god-valley-shadow", "L’Ombre de God Valley", "God Valley a traversé l’histoire sans briser ton équipage.", "Réussir l’intégralité de l’arc God Valley.", "legendary", "🌑", ({ game }) => game?.runMode === "story" && game?.storyId === "roger" && game?.legendaryArcs?.talent?.status === "succeeded"],
    ["story-roger-golden-lion-rival", "Dompteur du Lion d’Or", "La flotte de Shiki n’a pas refermé la mer sur ton pavillon.", "Réussir l’intégralité de l’arc Edd War.", "legendary", "🦁", ({ game }) => game?.runMode === "story" && game?.storyId === "roger" && game?.legendaryArcs?.marineford?.status === "succeeded"],
    ["story-roger-sea-titan", "Titan des mers", "Le choc des plus grandes volontés a fait trembler l’océan.", "Réussir l’intégralité de l’arc Le Choc des Titans.", "legendary", "🌊", ({ game }) => game?.runMode === "story" && game?.storyId === "roger" && game?.legendaryArcs?.emperor?.status === "succeeded"],
    ["story-roger-end-of-the-world", "Au bout du monde", "Laugh Tale existe désormais dans les souvenirs de cet équipage.", "Atteindre Laugh Tale.", "epic", "🏝️", ({ game }) => game?.runMode === "story" && game?.storyId === "roger" && game?.flags?.reachedLaughTale === true],
    ["story-roger-conquered-the-seas", "Celui qui conquit les mers", "Le voyage de Roger s’achève sur un héritage accompli, quel que soit le score final.", "Terminer l’histoire de Roger avec l’Héritage accompli.", "mythic", "👑", ({ game }) => game?.runMode === "story" && game?.storyId === "roger" && Boolean(game?.isFinished || game?.finishedAt || game?.endingType || game?.ending) && Boolean(game?.dreamCompleted ?? game?.ending?.dreamCompleted)],
    ["story-roger-legend-among-legends", "Légende parmi les légendes", "God Valley, Edd War et le Choc des Titans ont tous consacré la même traversée.", "Réussir les trois arcs légendaires au cours d’une même histoire de Roger.", "mythic", "✨", ({ game }) => game?.runMode === "story" && game?.storyId === "roger" && ["talent", "marineford", "emperor"].every((arcId) => game?.legendaryArcs?.[arcId]?.status === "succeeded")],
  ].map(([id, name, description, unlockHint, rarity, icon, condition]) => Object.freeze({
    id, name, description, unlockHint, category: "story-roger", rarity, icon,
    factions: ["pirate"], timing: "any", storyId: "roger", runMode: "story",
    sourceType: id.includes("god-valley") ? "story-legendary-talent" : id.includes("golden-lion") ? "story-legendary-marineford" : id.includes("sea-titan") ? "story-legendary-emperor" : "story-roger",
    effects: {}, ...(condition ? { condition } : {}),
  })),
  ...BLUE_LEGACY_BOSS_TITLES,
]);
