/* ==========================================================
   BLUE LEGACY — CATALOGUE DES TITRES
========================================================== */

const BLUE_LEGACY_BOSS_TITLES = Object.freeze([
  ["one-piece", "Cartographe de l’impossible", "pirate", "🧭"],
  ["sea-emperor", "Pavillon des mers libres", "pirate", "🏴‍☠️"],
  ["worlds-greatest-fortune", "Maître des cargaisons", "pirate", "💰"],
  ["forgotten-history", "Lecteur des traces interdites", "pirate", "📜"],
  ["greatest-bounty-hunter", "Référence des chasseurs", "bounty-hunter", "🎯"],
  ["most-dangerous-criminals", "Traqueur de l’impossible", "bounty-hunter", "⛓️"],
  ["hunt-an-emperor", "Chasseur de pavillons noirs", "bounty-hunter", "⚔️"],
  ["contract-fortune", "Arbitre des grands contrats", "bounty-hunter", "📜"],
  ["break-the-chains", "Briseur de convois", "revolutionary", "⛓️"],
  ["reveal-void-century", "Porteur des vérités interdites", "revolutionary", "🗿"],
  ["build-underground-network", "Nœud de la résistance", "revolutionary", "🕸️"],
  ["found-free-nation", "Voix d’un peuple libre", "revolutionary", "🕊️"],
  ["admiral", "Rempart des grandes routes", "marine", "⚓"],
  ["fleet-admiral", "Commandant des flottes", "marine", "🎖️"],
  ["reform-the-marines", "Officier de la justice nouvelle", "marine", "⚖️"],
  ["greatest-marine-hero", "Espoir des populations", "marine", "🛡️"],
].map(([dreamId, name, faction, icon]) => {
  const specialties = {
    "one-piece": "intelligence", "sea-emperor": "charisma",
    "worlds-greatest-fortune": "intelligence", "forgotten-history": "intelligence",
    "greatest-bounty-hunter": "combat", "most-dangerous-criminals": "intelligence",
    "hunt-an-emperor": "haki", "contract-fortune": "intelligence",
    "break-the-chains": "combat", "reveal-void-century": "intelligence",
    "build-underground-network": "intelligence", "found-free-nation": "charisma",
    admiral: "combat", "fleet-admiral": "charisma",
    "reform-the-marines": "intelligence", "greatest-marine-hero": "health",
  };
  const stat = specialties[dreamId];
  return Object.freeze({
  id: `boss-${dreamId}-turning-point`,
  name,
  description: "Une épreuve majeure a donné une nouvelle portée à cette destinée.",
  unlockHint: "Surmonter un tournant majeur lié à ce rêve.",
  category: "exploit",
  rarity: "epic",
  icon,
  factions: [faction],
  timing: "mid",
  effects: {
    immediate: { [stat]: 7 },
    passive: { type: "statGainModifier", stat, value: 0.1 },
    popularity: 5,
  },
  });
}));

window.SEA_OF_LEGENDS_TITLES = Object.freeze([
  {
    id: "ami-des-betes",
    name: "Ami des bêtes",
    description: "Même les compagnons les plus imprévisibles reconnaissent ta bonté.",
    unlockHint: "Libérer le chien naufragé et gagner sa confiance.",
    category: "crew",
    rarity: "uncommon",
    icon: "🐾",
    factions: [],
    timing: "early",
    effects: {
      immediate: { charisma: 3 },
      passive: { type: "statGainModifier", stat: "charisma", value: 0.05 },
      popularity: 2,
    },
  },
  {
    id: "roi-des-pirates",
    name: "Roi des Pirates",
    description: "Tu as atteint le sommet de la piraterie.",
    unlockHint: "Accomplir le rêve de trouver le One Piece au terme d’une aventure.",
    category: "ultimate",
    rarity: "mythic",
    icon: "👑",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "empereur-des-mers",
    name: "Empereur des mers",
    description: "Ton pavillon impose sa loi jusque sur les mers les plus hostiles.",
    unlockHint: "Accomplir le rêve de devenir un Empereur des mers.",
    category: "ultimate",
    rarity: "legendary",
    icon: "👑",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 10 },
  },
  {
    id: "seigneur-des-tresors",
    name: "Seigneur des trésors",
    description: "Les richesses les mieux gardées ont fini entre tes mains.",
    unlockHint: "Accomplir le rêve d’amasser la plus grande fortune du monde.",
    category: "ultimate",
    rarity: "legendary",
    icon: "💎",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 10 },
  },
  {
    id: "gardien-histoire-oubliee",
    name: "Gardien de l’Histoire oubliée",
    description: "Tu portes une vérité que le monde cherchait à effacer.",
    unlockHint: "Accomplir le rêve de découvrir l’Histoire oubliée.",
    category: "ultimate",
    rarity: "legendary",
    icon: "📜",
    factions: ["pirate"],
    secret: true,
    timing: "final",
    finalTitle: true,
    effects: { popularity: 10 },
  },
  {
    id: "legende-des-chasseurs",
    name: "Légende des chasseurs",
    description: "Aucune cible ne semble pouvoir échapper à ta traque.",
    unlockHint: "Accomplir le rêve de devenir le plus grand chasseur de primes.",
    category: "ultimate",
    rarity: "mythic",
    icon: "🎯",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "fleau-des-criminels",
    name: "Fléau des criminels",
    description: "Ton nom suffit à inquiéter les équipages recherchés.",
    unlockHint: "Accomplir le rêve de capturer les criminels les plus dangereux.",
    category: "ultimate",
    rarity: "epic",
    icon: "⛓️",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 8 },
  },
  {
    id: "tombeur-empereur",
    name: "Tombeur d’Empereur",
    description: "Tu as fait vaciller l’une des plus grandes puissances des mers.",
    unlockHint: "Accomplir le rêve de traquer un Empereur.",
    category: "ultimate",
    rarity: "legendary",
    icon: "⚔️",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 10 },
  },
  {
    id: "maitre-des-contrats",
    name: "Maître des contrats",
    description: "Les missions les plus impossibles trouvent leur conclusion entre tes mains.",
    unlockHint: "Accomplir le rêve d’amasser une fortune grâce aux contrats.",
    category: "ultimate",
    rarity: "epic",
    icon: "📜",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 8 },
  },
  {
    id: "chain-breaker",
    name: "Briseur de chaînes",
    description: "Tu as fait tomber les réseaux qui prospéraient sur l’asservissement des plus faibles.",
    unlockHint: "Accomplir le rêve « Briser les chaînes » au cours d’une aventure Révolutionnaire.",
    category: "ultimate",
    rarity: "mythic",
    icon: "🔓",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "truth-bearer",
    name: "Porteur de la vérité",
    description: "Tu as rendu au monde une histoire que le Gouvernement mondial voulait effacer.",
    unlockHint: "Accomplir le rêve « Révéler le Siècle oublié » au cours d’une aventure Révolutionnaire.",
    category: "ultimate",
    rarity: "mythic",
    icon: "📜",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "architect-of-revolution",
    name: "Architecte de la Révolution",
    description: "Tu as bâti un réseau capable de porter la Révolution jusque dans les mers les plus lointaines.",
    unlockHint: "Accomplir le rêve « Bâtir le plus grand réseau clandestin » au cours d’une aventure Révolutionnaire.",
    category: "ultimate",
    rarity: "mythic",
    icon: "🕸️",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "founder-of-free-people",
    name: "Fondateur du peuple libre",
    description: "Tu as offert à un peuple un territoire que nul maître ne pourra lui reprendre.",
    unlockHint: "Accomplir le rêve « Fonder une nation libre » au cours d’une aventure Révolutionnaire.",
    category: "ultimate",
    rarity: "mythic",
    icon: "🕊️",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "amiral",
    name: "Amiral",
    description: "La Marine t’a confié l’un de ses plus hauts rangs.",
    unlockHint: "Accomplir le rêve de devenir Amiral.",
    category: "ultimate",
    rarity: "epic",
    icon: "⚓",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 8 },
  },
  {
    id: "amiral-en-chef",
    name: "Amiral en chef",
    description: "Tu diriges désormais les forces de la Marine.",
    unlockHint: "Accomplir le rêve de devenir Amiral en chef.",
    category: "ultimate",
    rarity: "mythic",
    icon: "⚓",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 12 },
  },
  {
    id: "justice-nouvelle",
    name: "Justice nouvelle",
    description: "Ta vision de la justice transforme durablement la Marine.",
    unlockHint: "Accomplir le rêve de réformer la Marine.",
    category: "ultimate",
    rarity: "legendary",
    icon: "⚖️",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 10 },
  },
  {
    id: "heros-de-la-marine",
    name: "Héros de la Marine",
    description: "Les civils comme les soldats racontent désormais tes exploits.",
    unlockHint: "Accomplir le rêve de devenir le plus grand héros de la Marine.",
    category: "ultimate",
    rarity: "epic",
    icon: "🛡️",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 8 },
  },
  {
    id: "veteran-des-mers",
    name: "Vétéran des mers",
    description: "Deux années d’aventure ont forgé une carrière mémorable.",
    unlockHint: "Atteindre le terme des vingt-quatre mois d’une aventure.",
    category: "adventure",
    rarity: "rare",
    icon: "🧭",
    factions: [],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 4 },
  },
  {
    id: "destin-brise",
    name: "Destin brisé",
    description: "Une grande aventure interrompue avant son accomplissement.",
    unlockHint: "Voir une aventure s’achever à la suite de blessures mortelles.",
    category: "destiny",
    rarity: "common",
    icon: "🌊",
    factions: [],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 1 },
  },
  {
    id: "prisonnier-des-mers",
    name: "Prisonnier des mers",
    description: "La route s’est achevée derrière les barreaux.",
    unlockHint: "Voir une aventure prendre fin par une capture.",
    category: "destiny",
    rarity: "common",
    icon: "⛓️",
    factions: [],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 1 },
  },
  {
    id: "vaincu-par-les-mers",
    name: "Vaincu par les mers",
    description: "Les dangers du voyage ont finalement eu raison de toi.",
    unlockHint: "Voir une aventure s’achever par une défaite.",
    category: "destiny",
    rarity: "common",
    icon: "⚓",
    factions: [],
    timing: "final",
    finalTitle: true,
    effects: { popularity: 1 },
  },
  {
    id: "legende-inachevee",
    name: "Légende inachevée",
    description: "Ton voyage atteint son terme avant que ton rêve ne devienne réalité.",
    unlockHint: "Terminer une aventure avec moins de 60 de Popularité sans accomplir son rêve.",
    category: "destiny",
    rarity: "uncommon",
    icon: "📖",
    factions: [],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "capitaine-de-renom",
    name: "Capitaine de renom",
    description: "Ton pavillon n’a pas atteint son ambition ultime, mais son nom circule déjà bien au-delà de ton équipage.",
    unlockHint: "Terminer une aventure Pirate avec une Popularité comprise entre 60 et 74 sans accomplir son rêve.",
    category: "piracy",
    rarity: "rare",
    icon: "🏴‍☠️",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "terreurs-des-grandes-routes",
    name: "Terreur des grandes routes",
    description: "Les équipages comme les autorités ont appris à ne jamais ignorer ton pavillon.",
    unlockHint: "Terminer une aventure Pirate avec une Popularité comprise entre 75 et 89 sans accomplir son rêve.",
    category: "piracy",
    rarity: "epic",
    icon: "☠️",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "legende-des-mers",
    name: "Légende des mers",
    description: "Sans atteindre le rêve qui guidait ton voyage, tu es devenu une légende que toutes les mers racontent.",
    unlockHint: "Terminer une aventure Pirate avec au moins 90 de Popularité sans accomplir son rêve.",
    category: "piracy",
    rarity: "legendary",
    icon: "🌊",
    factions: ["pirate"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "officier-de-renom",
    name: "Officier de renom",
    description: "Ta carrière n’a pas atteint son objectif ultime, mais tes états de service inspirent déjà le respect.",
    unlockHint: "Terminer une aventure Marine avec une Popularité comprise entre 60 et 74 sans accomplir son rêve.",
    category: "marine",
    rarity: "rare",
    icon: "⚓",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "rempart-de-la-justice",
    name: "Rempart de la justice",
    description: "Soldats et civils se souviennent d’un officier resté debout lorsque la justice vacillait.",
    unlockHint: "Terminer une aventure Marine avec une Popularité comprise entre 75 et 89 sans accomplir son rêve.",
    category: "marine",
    rarity: "epic",
    icon: "🛡️",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "legende-de-la-marine",
    name: "Légende de la Marine",
    description: "Même sans accomplir ton ambition ultime, ton nom appartient désormais à l’histoire de la Marine.",
    unlockHint: "Terminer une aventure Marine avec au moins 90 de Popularité sans accomplir son rêve.",
    category: "marine",
    rarity: "legendary",
    icon: "⚓",
    factions: ["marine"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "chasseur-de-renom",
    name: "Chasseur de renom",
    description: "Tes contrats et tes captures ont bâti une réputation que les commanditaires prennent au sérieux.",
    unlockHint: "Terminer une aventure de Chasseur de primes avec une Popularité comprise entre 60 et 74 sans accomplir son rêve.",
    category: "bounty-hunting",
    rarity: "rare",
    icon: "🎯",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "maitre-de-la-traque",
    name: "Maître de la traque",
    description: "Les cibles les plus prudentes savent désormais que tu peux retrouver presque n’importe qui.",
    unlockHint: "Terminer une aventure de Chasseur de primes avec une Popularité comprise entre 75 et 89 sans accomplir son rêve.",
    category: "bounty-hunting",
    rarity: "epic",
    icon: "🔍",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "traqueur-de-legende",
    name: "Traqueur de légende",
    description: "Ton rêve est resté hors de portée, mais ta carrière est devenue une référence pour tous les chasseurs.",
    unlockHint: "Terminer une aventure de Chasseur de primes avec au moins 90 de Popularité sans accomplir son rêve.",
    category: "bounty-hunting",
    rarity: "legendary",
    icon: "🎯",
    factions: ["bounty-hunter"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "voix-de-la-revolte",
    name: "Voix de la révolte",
    description: "Ton rêve n’est pas entièrement réalisé, mais ta voix a éveillé des résistances qui ne s’éteindront plus.",
    unlockHint: "Terminer une aventure Révolutionnaire avec une Popularité comprise entre 60 et 74 sans accomplir son rêve.",
    category: "revolution",
    rarity: "rare",
    icon: "✊",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "etendard-de-la-liberte",
    name: "Étendard de la liberté",
    description: "Là où ton passage est connu, les opprimés savent désormais qu’une autre voie est possible.",
    unlockHint: "Terminer une aventure Révolutionnaire avec une Popularité comprise entre 75 et 89 sans accomplir son rêve.",
    category: "revolution",
    rarity: "epic",
    icon: "🚩",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "legende-de-la-revolution",
    name: "Légende de la Révolution",
    description: "Sans achever ton ambition ultime, tu as profondément marqué l’histoire de la lutte contre l’oppression.",
    unlockHint: "Terminer une aventure Révolutionnaire avec au moins 90 de Popularité sans accomplir son rêve.",
    category: "revolution",
    rarity: "legendary",
    icon: "🔥",
    factions: ["revolutionary"],
    timing: "final",
    finalTitle: true,
    effects: {},
  },
  {
    id: "navigateur-routes-impossibles",
    name: "Navigateur des routes impossibles",
    description: "Les courants les plus capricieux n’effacent plus ta route.",
    unlockHint: "Atteindre le Nouveau Monde au cours d’une aventure.",
    category: "exploration",
    rarity: "rare",
    icon: "🧭",
    factions: [],
    timing: "late",
    effects: {
      immediate: { intelligence: 6 },
      passive: { type: "statGainModifier", stat: "intelligence", value: 0.08 },
      popularity: 5,
    },
    condition: ({ game }) => Boolean(game?.visitedZoneIds?.includes("shinsekai")),
  },
  {
    id: "volonte-acier",
    name: "Volonté d’acier",
    description: "Ton Haki témoigne d’une volonté longuement éprouvée.",
    unlockHint: "Atteindre 45 en Haki.",
    category: "combat",
    rarity: "epic",
    icon: "🛡️",
    factions: [],
    timing: "late",
    effects: {
      immediate: { haki: 8 },
      passive: { type: "statGainModifier", stat: "haki", value: 0.1 },
      popularity: 7,
    },
    condition: ({ game }) => Number(game?.stats?.haki) >= 45,
  },
  {
    id: "compagnon-legende",
    name: "Compagnon de légende",
    description: "Un équipage nombreux a choisi de poursuivre cette aventure à tes côtés.",
    unlockHint: "Réunir au moins quatre membres d’équipage.",
    category: "crew",
    rarity: "rare",
    icon: "👥",
    factions: [],
    timing: "mid",
    effects: {
      immediate: { charisma: 5 },
      passive: { type: "statGainModifier", stat: "charisma", value: 0.08 },
      popularity: 4,
    },
    condition: ({ game }) => Number(game?.stats?.crew) >= 4,
  },
  {
    id: "stratege-des-courants",
    name: "Stratège des courants",
    description: "Tes plans ouvrent des routes que la force seule ne saurait atteindre.",
    unlockHint: "Atteindre 55 en Intelligence.",
    category: "exploration",
    rarity: "rare",
    icon: "🧠",
    factions: [],
    timing: "mid",
    effects: {
      immediate: { intelligence: 6 },
      passive: { type: "statGainModifier", stat: "intelligence", value: 0.1 },
      popularity: 5,
    },
    condition: ({ game }) => Number(game?.stats?.intelligence) >= 55,
  },
  {
    id: "voix-des-equipages",
    name: "Voix des équipages",
    description: "Des inconnus choisissent de te suivre lorsqu’ils entendent ton appel.",
    unlockHint: "Atteindre 70 en Charisme.",
    category: "crew",
    rarity: "rare",
    icon: "✨",
    factions: [],
    timing: "late",
    effects: {
      immediate: { charisma: 8 },
      passive: { type: "statGainModifier", stat: "charisma", value: 0.1 },
      popularity: 7,
    },
    condition: ({ game }) => Number(game?.stats?.charisma) >= 70,
  },
  {
    id: "combattant-grand-line",
    name: "Combattant de Grand Line",
    description: "Les affrontements successifs ont fait de toi une référence au combat.",
    unlockHint: "Atteindre 60 en Combat.",
    category: "combat",
    rarity: "rare",
    icon: "⚔️",
    factions: [],
    timing: "mid",
    effects: {
      immediate: { combat: 6 },
      passive: { type: "statGainModifier", stat: "combat", value: 0.1 },
      popularity: 5,
    },
    condition: ({ game }) => Number(game?.stats?.combat) >= 60,
  },
  {
    id: "survivant-cent-tempetes",
    name: "Survivant des cent tempêtes",
    description: "Ton endurance est devenue aussi célèbre que les dangers traversés.",
    unlockHint: "Atteindre 80 en Santé après avoir survécu à un événement dangereux.",
    category: "destiny",
    rarity: "epic",
    icon: "❤️",
    factions: [],
    timing: "late",
    effects: {
      immediate: { health: 8 },
      passive: { type: "statGainModifier", stat: "health", value: 0.1 },
      popularity: 7,
    },
    condition: ({ game }) => Number(game?.stats?.health) >= 80 &&
      Number(game?.achievementProgress?.dangerEventsSurvived) >= 1,
  },
  ...BLUE_LEGACY_BOSS_TITLES,
]);
